# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: shoppingCart
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTI1Zjg0YTg2Y2U4M2I4NTFkYzA0MmEwYWI2MGZkNmNkY2Y3NjhhMDM0MThmMDZiNmJhYzU3MzA5NjJkZjkwNTU2OWM4MDYxODQ3ZjdmOTdjYmRmMGQ3MjIyODFhYWMyOWQwMTJhNThkMGZlOWNhNDNiYWMzNmRiMWMxYmU5NDg=
