package com.poc.elk.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TestEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestEntityAllPropertiesEquals(TestEntity expected, TestEntity actual) {
        assertTestEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertTestEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestEntityAllUpdatablePropertiesEquals(TestEntity expected, TestEntity actual) {
        assertTestEntityUpdatableFieldsEquals(expected, actual);
        assertTestEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestEntityAutoGeneratedPropertiesEquals(TestEntity expected, TestEntity actual) {
        assertThat(actual)
            .as("Verify TestEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestEntityUpdatableFieldsEquals(TestEntity expected, TestEntity actual) {
        assertThat(actual)
            .as("Verify TestEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestEntityUpdatableRelationshipsEquals(TestEntity expected, TestEntity actual) {
        // empty method
    }
}
