name: shopping-cart-jenkins

services:
  jenkins:
    build: .
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    group_add:
      - "${DOCKER_SOCKET_GID:-0}"
    volumes:
      - jenkins-home:/var/jenkins_home
      - ${DOCKER_DESKTOP_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock

volumes:
  jenkins-home:
